import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

// The CSS variable names are deliberately font-neutral. `blueprint preset` swaps
// which next/font/google export feeds each one; nothing downstream has to change.
const fontSans = Geist({
  variable: "--font-app-sans",
  subsets: ["latin"],
});

const fontMono = Geist_Mono({
  variable: "--font-app-mono",
  subsets: ["latin"],
});

const fontHeading = Instrument_Sans({
  variable: "--font-app-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        fontSans.variable,
        fontMono.variable,
        fontHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
